---
title: Baseline standards for accessible educational content and practice for science,
  technology, engineering, mathematics, and medicine (STEMM) education
author: Tara Chattaway<sup>1</sup>, Darren Paskell<sup>1</sup>, George Rhodes<sup>2</sup>,
  Jim Tyson<sup>3</sup>, Ben Watson<sup>3</sup>
date: "2023-04-26"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

**October 2022**^[Thomas Pocklington Trust<sup>1</sup>, University of Westminster<sup>2</sup>, University College London (UCL)<sup>3</sup>]

## Introduction

The proposal addresses accessibility of educational content specifically with respect to the STEMM disciplines. We use the acronym, for **science, technology, engineering, and mathematics and medicine (STEMM)**, acknowledging that the issues affect a broader community than this. We also raise the issue of **accessible coding**, which is not as often addressed as other, better understood issues.

The topics covered in these guides are specific to STEMM and we set out the standard where possible giving links to help in meeting it.

This proposal is the product of a small group with interests in technology, accessibility, inclusivity, and pedagogy. We welcome comment, criticism, and hope that the wider community will contribute to further development.

## Specific guidance for readers

### Students

This document is offered to students to

-   Guide student expectations as to what accommodations and adjustments they should expect;

-   Facilitate conversations around expectations;

-   Enable students themselves to produce their own more accessible content.

### Lecturers

This document is intended to set a simple standard for embedding basic accessibility priorities in STEMM content.

The document can help you understand what you should do to enable inclusive learning and gives links as to how you can do it.

There are also some general considerations that apply:

-   Understand who is responsible for implementing policy including

    -   Who assigns the resources necessary;

    -   Who provides the knowledge required to implement standards.

-   Software may be accessible to different subsets of users, for example, screen reader users vs magnification users;

-   Sometimes something perceived to be an accessibility issue is an issue with fluency with assistive technology and students should be provided with opportunities to familiarize themselves with technology;

-   Timeliness is important:

    -   Provide materials in time;

    -   Consider assignment timings;

    -   Where students may need training, provide knowledge in time.

The issues and remedies identified apply across sectors and not just to universities. An institution wide approach is needed since consistency helps support accessibility.

In general, it cannot be the sole responsibility of the student to ensure that they can access materials.

Consider issues that may arise in assessment or examination situations. For example, ensure that students using large print formats have adequate space.

We assume that creators of content will already be aware of general issues in accessibility in education and that there is a commitment to the POUR framework that underpins the [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/TR/WCAG21/).

## Supporting STEMM Learning Content

The guidance is designed for anyone creating STEMM content that has technical data, code, or language. Links are contained within each of the baseline topics for more in-depth instruction.

Content, materials, and practices should be:

-   **Perceivable**: all content consumers can at least perceive the material.

-   **Operable**: all content users can navigate and interact with material.

-   **Understandable**: all content users can understand the material.

-   **Robust**: all content users can access and interact with the formats used for presentation of material.

We add a STEMM focus:

**All users can access and interact with STEMM content where necessary using assistive technologies.**

Sample guidance for non-STEMM content in general can be found in several places, for example on [UCL's accessibility website](https://bit.ly/UCLDigitalInclusion) (<https://bit.ly/UCLDigitalInclusion>).

## Topics

### Mathematical or discipline specific technical content

-   Equations are perceivable and can be read by screen readers, are accompanied by a version in natural language, or in plain text format as a last resort. This applies to other formal disciplines (e.g., linguistics and logic) and in the natural sciences where specialist notations are used;

-   Where documents are provided in large format, equations etc must also be enlarged and should therefore be created in formats that can be re-sized;

-   Where documents are provided in large format, formatting and cross-referencing consistency must be maintained;

-   Directions for accessing the content are available (and themselves in an accessible format);

-   Content can be converted to alternative formats that students can interact with and access as they need;

-   Content is provided in accessible print versions for learners who cannot access electronic versions.

#### Resources

[Advance HE (Higher Education) collection on inclusive Mathematics curricula](https://tinyurl.com/clifeeandrowlett)

(<https://tinyurl.com/clifeeandrowlett>)

[MathJax Demo](https://tinyurl.com/mathjaxdemo)

(<https://tinyurl.com/mathjaxdemo>)

[MathML Introduction](https://bit.ly/W3MathML)

(<https://bit.ly/W3MathML>)

[MathML Basics](https://bit.ly/MathMLBasics)

(<https://bit.ly/MathMLBasics>)

[Making equations accessible at the University of York (v2.7)](https://bit.ly/Equations4All)

(<https://bit.ly/Equations4All>)

[A11yMaths GitHub University Resources Collection](https://bit.ly/A11yMaths)

(<https://bit.ly/A11yMaths>)

### Data visualisations

-   Provide visualisations of adequate resolution. Low resolution screenshots are not suitable;

-   All visualisations include captions and where possible alternative text descriptions;

-   The context and educational importance of the content should be clear using only the text or caption;

-   Colour is not used in visualisations as the only means of interpreting data;

-   Be aware of the consequences of colour choice in visualisations. Consider colour combinations that affect colour blind users, for example red-green combinations;

-   Use high contrasting colours for labelling and data;

-   The original data on which visualisations are based ~~is~~ should be available in an accessible format where possible;

-   Consider the feasibility of providing tactile images;

-   If tactile images are used, carefully consider scale and resolution, and provide adequate labelling that works in all tactile media.

#### Resources

[A Comprehensive Guide to Accessible Data Visualization](https://bit.ly/comprehensivedataviz)

(<https://bit.ly/comprehensivedataviz>)

[More Accessible Data Visualizations](https://bit.ly/moreaccessibleviz)

(<https://bit.ly/moreaccessibleviz>)

[Writing alternative text for data visualisations](https://bit.ly/attextviz)

(<https://bit.ly/attextviz>)

[Alt text from](https://bit.ly/ONSAltText) ONS (Office of National Statistics)

(<https://bit.ly/ONSAltText>)

[Alternate Text for STEM (Science, Technology, Engineering and Maths) Example](https://bit.ly/AltTextExamples)

(<https://bit.ly/AltTextExamples>)

### Tables

-   If large tables of data are essential, provide alternative format summaries of data;

-   Signpost clearly for learners if it is important that they read complete tables of data. Large tables are difficult for:

    -   Students who experience reading disabilities, such as dyslexia;

    -   Students who rely on magnification of documents;

    -   Students who navigate tables without sight, or who use of a screen reader.

-   Consider moving large tables of data to appendices;

-   Ensure that there are relevant headings for all columns and all rows;

-   All data headings should appear on every page;

-   Headings and names of data items are distinguished from data values;

-   There are no blank or merged cells. **Where data are missing this is shown**. Zero counts are shown as zero (and not left blank);

-   Where possible, avoid nested tables;

-   All tables include captions and titles, and where possible alternative text descriptions;

-   The context and educational importance of the content should be clear using only the alternative text or caption;

-   The table is navigable -- the **tab order** of the cells is correct when read by software or navigated by keyboard alone.

#### Resources

[Creating Accessible Tables](https://bit.ly/MSTables)

(<https://bit.ly/MSTables>)

[Aston -- Accessible Tables](https://bit.ly/AstonTables)

(<https://bit.ly/AstonTables>)

[Techniques for tables](https://bit.ly/SimplestTables)

(<https://bit.ly/SimplestTables>)

[Accessible Tables -- Welsh Government Guide](https://bit.ly/TablesWalesGov)

(<https://bit.ly/TablesWalesGov>)

[Alternate Text for STEM Example](https://bit.ly/AltTextExamples)

(<https://bit.ly/AltTextExamples>)

### Scientific Images

-   Provide images of adequate resolution. Low resolution images are not suitable;

-   Where documents are provided in large format, images etc must also be enlarged and should therefore be created in formats that can be re-sized;

-   Where documents are provided in large format, formatting and cross-referencing consistency must be maintained;

-   Be aware of the consequences of colour choice in images. Consider colour combinations that affect colour blind users, for example red-green combinations;

-   In non-photographic illustration avoid contrasts that may be a problem for disabled viewers. Use high contrasting colours for labelling and data;

-   Provide the context and purpose of the image in the alternative text, if not already described in context in surrounding text;

-   Where images contain text, that text should be included in any alternative text or surrounding text descriptions;

-   Where the image conveys complex information, consider describing the complexity in detail in alternative text or include it in the main commentary.

#### Resources

[Good Practice on Inclusive Curricula in the Mathematical Sciences](https://bit.ly/colorandcontrast)

(<https://bit.ly/colorandcontrast>)

[Colour blindness](https://bit.ly/colour-blindess)

(<https://bit.ly/colour-blindess>)

### Scientific video

-   For rehearsed video, consider the interaction of foreground and background colour for viewers (e.g., green shirt against a red background) and how they may interact with caption colours;

-   Effective audio description in video should be brief, clear, relevant, and included in any transcription;

-   Presenters and narrators should ensure that any on screen activity is described either verbally or in text/transcript form (e.g., the steps of an experiment, images/videos/other visuals, graphs etc);

-   For accurate closed captions or transcripts:

    -   Don't rely on auto-transcription for technical domains. Always post-edit for correct terminology.

    -   If using a transcription, captioning or sign interpretation service, provide them with a technical glossary in advance;

-   Aim for clearest sound quality and little or no background noise.

#### Resources

[Checklist for Creating Accessible Videos](https://tinyurl.com/accessiblevideochecklist)

(<https://tinyurl.com/accessiblevideochecklist>)

### Maps

We assume that complex technology is not easily available to many content creators to produce tactile, audio-tactile, braille or augmented paper maps.

-   Provide maps of adequate resolution. Low resolution screenshots are not suitable;

-   All maps should include captions and where possible alternative text descriptions. For example, directions in a navigational map, or summary description for information maps;

-   Where the maps convey complex information, consider describing the complexity in detail or include it in the main commentary;

-   The context and educational importance of the content should be clear using only the text or caption;

-   Colour is not used in maps as the only means of interpreting data;

-   Be aware of the consequences of colour choice in maps. Consider colour combinations that affect colour blind users, for example red-green combinations;

-   Use high contrasting colours for labelling and data;

-   Consider the feasibility of providing tactile maps;

-   If tactile maps are used, carefully consider scale and resolution, and provide adequate labelling that works in all tactile media;

<!-- -->

-   Where documents are provided in large format, maps must also be enlarged and should therefore be created in formats that can be re-sized;

-   Where documents are provided in large format, formatting and cross-referencing consistency must be maintained;

-   Ensure that symbols, markers and labelling on maps is large enough and distinct enough to be **perceived** and differentiated easily;

<!-- -->

-   Different criteria apply depending on context of use. Where screen readers may be used, consider the reading order of graphical objects;

-   Maps provided in special formats (tactile, etc) may require training to be useful to users.

#### Resources

[WC3 Accessible Maps](https://bit.ly/AccessibleMaps)

(<https://bit.ly/AccessibleMaps>)

### Coding

-   Students need guidance on the use of complex coding applications as well as on writing code;

-   Enable informed user choice when recommending software systems such as integrated development environments (IDEs);

-   Simple interfaces will generally be more useable for screen reader users;

-   Systems where users can select an editor that suits their needs are preferable to those where no choice is possible;

-   Ensure that students understand the use of syntax highlighting;

-   Try to select systems of syntax highlighting that can be understood by screen reader users;

-   Systems where output can be produced in screen readable documents (rather than just as command line output) are preferred.

#### Resources

[Accessible coding tips](https://bit.ly/accessiblecodingtips)

(<https://bit.ly/accessiblecodingtips>)

## General Links

[Improving the accessibility of Science, Technology, Engineering, Mathematics and Medicine](https://bit.ly/improvestemaccessibility)

(<https://bit.ly/improvestemaccessibility>)

[JISC Maths Accessibility Special Interest Group](https://bit.ly/A11yMaths)

(<https://bit.ly/A11yMaths>)

[Bheard New Technologies](https://bheardu.net/new-technologies/)

(<https://bheardu.net/new-technologies/>)
